curvefi/curve-contract

contracts/testing/GaugeControllerMock.vy, contracts/testing/LiquidityGaugeMock.vy, contracts/testing/README.md, contracts/testing/Registry.vy, scripts/utils.py, tests/common/integration/test_registry.py, tests/conftest.py
* add unit tests to check pool compatibility with the registry contract
=> Registry tests

brownie_hooks.py, contracts/pool-templates/DepositYLend.vy, contracts/pool-templates/README.md, contracts/pool-templates/StableSwapBase.vy, contracts/pool-templates/StableSwapYLend.vy
* add depositor contract template
=> Depositor template

.github/workflows/main.yaml, contracts/tokens/CurveTokenV2.vy, tests/common/unitary/test_exchange_underlying.py, tests/common/unitary/test_exchange_underlying_reverts.py, tests/conftest.py, tests/token/conftest.py, tests/token/test_approve.py, tests/token/test_mint_burn.py, tests/token/test_transfer.py, tests/token/test_transferFrom.py, tests/token/test_version2.py
* tests for `exchange_underlying`
* tests for LP tokens
=> Unit tests

contracts/pools/README.md, contracts/pools/hbtc/README.md, contracts/pools/hbtc/StableSwapHBTC.vy, contracts/pools/hbtc/pooldata.json, tests/common/integration/test_exchange.py, tests/common/unitary/test_exchange_underlying.py, tests/common/unitary/test_exchange_underlying_reverts.py, tests/common/unitary/test_modify_fees.py
* Add the [hBTC pool](https://www.curve.fi/hbtc)
* update test cases
=> Add hBTC pool

contracts/pool-templates/StableSwapBase.vy, contracts/pool-templates/StableSwapYLend.vy
* minor optimizations / readability edits to templates
=> Optimize templates

contracts/pool-templates/StableSwapBase.vy, tests/pools/common/unitary/test_ramp_A_precise.py
=> More precise ramp of A in pool template

contracts/pool-templates/StableSwapYLend.vy, tests/pools/common/unitary/test_ramp_A.py, tests/pools/common/unitary/test_ramp_A_precise.py
Apply changes in #37 to the y-lending template.
=> Precise ramping of A in y-lend template

contracts/pool-templates/StableSwapBase.vy, contracts/pools/3pool/README.md, contracts/pools/README.md, contracts/pools/busd/README.md, contracts/pools/compound/README.md, contracts/pools/hbtc/README.md, contracts/pools/pax/README.md, contracts/pools/ren/README.md, contracts/pools/sbtc/README.md, contracts/pools/susd/README.md, contracts/pools/usdt/README.md, contracts/pools/y/README.md, contracts/testing/cERC20.vy, contracts/testing/renERC20.vy, contracts/testing/yERC20.vy, scripts/deploy.py, tests/fixtures/deployments.py
* updates to deployment script
* add liquidity gauge info in pool readmes
* update test ERC20's to use vyper 0.2.x
* minor gas optimizations in base template
=> Misc updates

contracts/pool-templates/StableSwapYLend.vy, contracts/pools/snow/StableSwapSnow.vy, tests/pools/common/integration/test_simulate_exchange.py, tests/pools/common/integration/test_virtual_price_increases.py, tests/pools/common/unitary/test_get_virtual_price.py, tests/pools/common/unitary/test_remove_liquidity_one_coin.py
* Add unit and integration testing around virtual price - number go up!
* Fix a bug in `_calc_withdraw_one_coin` where rates were not properly considered
Run tests.
=> Virtual price

contracts/testing/Registry.vy
Update the registry contract used for testing, based on changes from https://github.com/curvefi/curve-pool-registry/pull/8
=> feat: update registry

contracts/pool-templates/base/SwapTemplateBase.vy, contracts/pool-templates/meta/DepositTemplateMeta.vy, contracts/pool-templates/meta/SwapTemplateMeta.vy, contracts/pool-templates/y/DepositTemplateY.vy, contracts/pool-templates/y/SwapTemplateY.vy, tests/pools/common/integration/test_virtual_price_increases.py
Optimize templates for smaller deployment size, based on changes in Vyper 0.2.5
* Grouping memory zero'ing statements
* Moving private function calls earlier in the execution to reduce the size of memory
* Creating new memory variables to avoid repeated array offset calculations
Run tests.
=> Template optimizations

contracts/pools/y/README.md
Noticed the docs listed the wrong address for yDAI, yUSDC, and yUSDT. yTUSD was correct
Changed it
Check for yourself!
=> Update yVault addresses for y pool

contracts/pool-templates/meta/SwapTemplateMeta.vy, contracts/pools/gusd/StableSwapGUSD.vy, contracts/pools/husd/StableSwapHUSD.vy, contracts/pools/usdk/StableSwapUSDK.vy, contracts/pools/usdn/StableSwapUSDN.vy
=> Add TokenExchangeUnderlying

contracts/pool-templates/base/SwapTemplateBase.vy, contracts/pool-templates/meta/DepositTemplateMeta.vy, contracts/pool-templates/meta/SwapTemplateMeta.vy, contracts/pool-templates/y/DepositTemplateY.vy, contracts/pool-templates/y/SwapTemplateY.vy, contracts/pools/gusd/DepositGUSD.vy, contracts/pools/gusd/StableSwapGUSD.vy, contracts/pools/husd/DepositHUSD.vy, contracts/pools/husd/StableSwapHUSD.vy, contracts/pools/usdk/DepositUSDK.vy, contracts/pools/usdk/StableSwapUSDK.vy, contracts/pools/usdn/DepositUSDN.vy, contracts/pools/usdn/StableSwapUSDN.vy
Add return values to various methods within the swap templates and metapools.
These are useful for an accurate calculation of tokens received during swaps, or when adding or removing liquidity.
Run tests.
=> Feat return values

contracts/pool-templates/base/SwapTemplateBase.vy, contracts/pool-templates/meta/DepositTemplateMeta.vy, contracts/pool-templates/meta/SwapTemplateMeta.vy, contracts/pool-templates/y/SwapTemplateY.vy, contracts/pools/gusd/DepositGUSD.vy, contracts/pools/gusd/StableSwapGUSD.vy, contracts/pools/husd/DepositHUSD.vy, contracts/pools/husd/StableSwapHUSD.vy, contracts/pools/usdk/DepositUSDK.vy, contracts/pools/usdk/StableSwapUSDK.vy, contracts/pools/usdn/DepositUSDN.vy, contracts/pools/usdn/StableSwapUSDN.vy
Add natspec to the template contracts and pending metapools.
=> Add natspec

contracts/pool-templates/meta/DepositTemplateMeta.vy
=> Number of base coin is not necessarily 1

contracts/pool-templates/meta/DepositTemplateMeta.vy, contracts/pool-templates/meta/SwapTemplateMeta.vy, contracts/pools/gusd/StableSwapGUSD.vy, contracts/pools/husd/StableSwapHUSD.vy, contracts/pools/usdk/StableSwapUSDK.vy, contracts/pools/usdn/StableSwapUSDN.vy, tests/conftest.py, tests/pools/common/unitary/test_rate_caching.py
* Add tests for caching
* Adjust logic for private function calls
=> Caching tests

contracts/pool-templates/base/SwapTemplateBase.vy, contracts/pool-templates/meta/SwapTemplateMeta.vy, contracts/pools/gusd/StableSwapGUSD.vy, contracts/pools/husd/StableSwapHUSD.vy, contracts/pools/usdk/StableSwapUSDK.vy, contracts/pools/usdn/StableSwapUSDN.vy
=> Add token_supply to RemoveLiquidityOne event

contracts/pool-templates/meta/DepositTemplateMeta.vy, contracts/pools/gusd/DepositGUSD.vy, contracts/pools/husd/DepositHUSD.vy, contracts/pools/usdk/DepositUSDK.vy, contracts/pools/usdn/DepositUSDN.vy, tests/zaps/common/test_remove_liquidity_imbalance_zap.py
=> remove_liquidity_imbalance added to the deposit zap for metapools

contracts/gauges/LiquidityGauge.vy, contracts/gauges/LiquidityGaugeReward.vy, scripts/deploy.py
Port killable gauges update from https://github.com/curvefi/curve-dao-contracts/pull/43
=> Killable gauges

contracts/pool-templates/meta/DepositTemplateMeta.vy, contracts/pool-templates/meta/SwapTemplateMeta.vy
Minor edits to metapool template based on vyper 0.2.6 release.
=> Update meta template for vyper 0.2.6

contracts/pools/busd/pooldata.json, contracts/pools/compound/pooldata.json, contracts/pools/gusd/pooldata.json, contracts/pools/hbtc/pooldata.json, contracts/pools/husd/pooldata.json, contracts/pools/linkusd/pooldata.json, contracts/pools/musd/README.md, contracts/pools/musd/pooldata.json, contracts/pools/pax/pooldata.json, contracts/pools/ren/pooldata.json, contracts/pools/sbtc/pooldata.json, contracts/pools/susd/pooldata.json, contracts/pools/usdk/pooldata.json, contracts/pools/usdn/pooldata.json, contracts/pools/usdt/pooldata.json, contracts/pools/y/pooldata.json
Add deployment addresses to `pooldata.json` for each pool.
=> Add deployments to pooldata.json

.github/workflows/rsv.yaml, contracts/pools/README.md, contracts/pools/rsv/DepositRSV.vy, contracts/pools/rsv/README.md, contracts/pools/rsv/StableSwapRSV.vy, contracts/pools/rsv/pooldata.json, tests/fixtures/coins.py, tests/test_gas.py
* Add the RSV metapool contracts and deployment info.
* Expand the gas profiling test to include actions that are less gas optimized (and more likely in the wild).
=> Add RSV metapool

brownie_hooks.py, contracts/pool-templates/meta/SwapTemplateMeta.vy
Remove unused constants from meta template and compiler hooks.
=> Remove unused constants

contracts/pools/musd/README.md
Fix the link for the mUSD pool readme to the mUSD contract address
-
https://etherscan.io/address/0xe2f2a5C287993345a840Db3B0845fbC70f5935a5
=> Fix link to mUSD contract

contracts/pool-templates/base/SwapTemplateBase.vy, contracts/pool-templates/meta/SwapTemplateMeta.vy, contracts/pool-templates/y/SwapTemplateY.vy, contracts/pools/tbtc/StableSwapTBTC.vy, contracts/tokens/CurveTokenV2.vy
=> Make LP token an minter public

contracts/pools/README.md, contracts/pools/rsv/pooldata.json, contracts/pools/tbtc/README.md, contracts/pools/tbtc/pooldata.json
* Update deployment addresses in `README.md` and `pooldata.json` for RSV and tBTC pools
* Update information about `pooldata.json` format in main pool readme.
=> Add addresses for RSV and tBTC pools

contracts/pools/gusd/README.md, contracts/pools/gusd/pooldata.json, contracts/pools/husd/README.md, contracts/pools/husd/pooldata.json, contracts/pools/linkusd/README.md, contracts/pools/linkusd/pooldata.json, contracts/pools/musd/README.md, contracts/pools/musd/pooldata.json, contracts/pools/rsv/README.md, contracts/pools/rsv/pooldata.json, contracts/pools/tbtc/README.md, contracts/pools/tbtc/pooldata.json, contracts/pools/usdk/README.md, contracts/pools/usdk/pooldata.json, contracts/pools/usdn/README.md, contracts/pools/usdn/pooldata.json
Update the metapool zap addresses.
=> Update metapool zap deployment addresses

contracts/pools/3pool/pooldata.json, contracts/pools/busd/pooldata.json, contracts/pools/compound/pooldata.json, contracts/pools/gusd/pooldata.json, contracts/pools/hbtc/pooldata.json, contracts/pools/husd/pooldata.json, contracts/pools/linkusd/pooldata.json, contracts/pools/musd/pooldata.json, contracts/pools/pax/pooldata.json, contracts/pools/ren/pooldata.json, contracts/pools/rsv/pooldata.json, contracts/pools/sbtc/pooldata.json, contracts/pools/susd/pooldata.json, contracts/pools/tbtc/pooldata.json, contracts/pools/usdk/pooldata.json, contracts/pools/usdn/pooldata.json, contracts/pools/usdt/pooldata.json, contracts/pools/y/pooldata.json
Add `LiquidityGauge` addresses to `pooldata.json` for each pool.
=> Add gauge addresses to pooldata

contracts/pools/tbtc/README.md, contracts/pools/tbtc/StableSwapTBTC.vy, contracts/pools/tbtc/pooldata.json
Change several pool references in comments and `pooldata.json` for tBTC pool
=> fix: change references to other pools -> tbtc

tests/pools/common/integration/test_curve.py, tests/pools/common/integration/test_simulate_exchange.py
Update the integration tests common to all pools.
* Updated the tests to make use of fixtures that weren't originally available when they were written
* In `simulated_exchange`, refactor out some of the logic into a setup fixture to reduce execution time
* Use `_mint_for_testing` instead of `mint` to simplify compatibility across pools
Confirm in the CI that tests are still passing for all pools.
=> Integration test updates

.github/workflows/pbtc.yaml, contracts/pools/pbtc/DepositPBTC.vy, contracts/pools/pbtc/README.md, contracts/pools/pbtc/StableSwapPBTC.vy, contracts/pools/pbtc/pooldata.json, tests/fixtures/coins.py
Implement the pBTC metapool - https://gov.curve.fi/t/scip-15-pbtc-sbtc-lp-metapool/1124
The pool is a minor tweak of existing logic for tBTC, only minor changes were required.
Run the tests. I've added a pBTC worker to the CI.
=> Add pBTC metapool

tests/pools/common/integration/test_virtual_price_increases.py
Add a rule for ramping A in the virtual price integration test.
Run the integration tests.
=> Ramp A during integration test

scripts/deploy.py
Updates to the deployment script.
* update the owner address to the current deployment of `PoolProxy`
* handle gas price with a scaling gas strategy
* update token deployment kwargs based on #93 
Deploy a pool.
=> Update deployment script

.github/workflows/bbtc.yaml, contracts/pools/bbtc/DepositBBTC.vy, contracts/pools/bbtc/README.md, contracts/pools/bbtc/StableSwapBBTC.vy, contracts/pools/bbtc/pooldata.json
Implement the BBTC metapool - https://gov.curve.fi/t/scip-10-adding-a-metapool-for-bbtc-binance-btc/1080
The pool is a minor tweak of existing logic for tBTC, only minor changes were required.
Run the tests. I've added a BBTC worker to the CI.
=> Add BBTC metapool

contracts/pools/pbtc/README.md, contracts/pools/pbtc/pooldata.json
Update the gauge address for pBTC pool
=> Update pBTC gauge address

.github/workflows/obtc.yaml, contracts/pools/obtc/DepositOBTC.vy, contracts/pools/obtc/README.md, contracts/pools/obtc/StableSwapOBTC.vy, contracts/pools/obtc/pooldata.json
=> Add oBTC pool

contracts/pools/bbtc/README.md
=> fix: update BBTC gauge address

contracts/pool-templates/base/SwapTemplateBase.vy, contracts/pool-templates/meta/SwapTemplateMeta.vy, contracts/pool-templates/y/SwapTemplateY.vy, tests/pools/common/integration/test_heavily_imbalanced.py
Revert on non-convergence of D or Y.  This can only happen in an extreme edge-case, as evidenced by the test I've added.
Confirm the test suite is passing, specifically for the templates.
=> Revert on non-convergence of D or Y

.github/workflows/ust.yaml, contracts/pools/ust/DepositUST.vy, contracts/pools/ust/README.md, contracts/pools/ust/StableSwapUST.vy, contracts/pools/ust/pooldata.json
Add a metapool for [Terra UST](http://terra.money/)
The pool is a minimal modification of the existing metapool template. It uses 3pool as a base.
Confirm that the tests are passing within the CI.
=> Add UST pool

.github/workflows/eurs.yaml, contracts/pools/eurs/README.md, contracts/pools/eurs/StableSwapEURS.vy, contracts/pools/eurs/pooldata.json
Add a euro-denominated pool for swaps between Statis [EURS](https://eurs.stasis.net/) and Synthetix sEUR.
The pool is a minimal modification of the existing base template.
Confirm that all tests are passing within the CI.
=> Add EURS/sEUR pool

README.md
=> Exclude python 3.9

tests/pools/common/unitary/test_add_liquidity.py, tests/pools/common/unitary/test_remove_liquidity.py, tests/pools/common/unitary/test_remove_liquidity_imbalance.py, tests/pools/common/unitary/test_remove_liquidity_one_coin.py
Add tests for events related to adding and removing liquidity.
Confirm that the CI is still passing.
=> Add tests for event logs on add/remove liquidity

.github/workflows/idle.yaml, contracts/pools/idle/README.md, contracts/pools/idle/StableSwapIDLE.vy, contracts/pools/idle/pooldata.json, contracts/pools/pbtc/pooldata.json, contracts/testing/IdleToken.vy, contracts/testing/LiquidityGaugeV2Mock.vy, tests/conftest.py, tests/fixtures/deployments.py, tests/pools/idle/test_add_liquidity_underlying.py, tests/pools/idle/test_claim_rewards.py, tests/pools/idle/test_remove_liquidity_imbalance_underlying.py, tests/pools/idle/test_remove_liquidity_one_coin_underlying.py, tests/pools/idle/test_remove_liquidity_underlying.py, tests/pools/idle/test_rewards_admin.py, tests/pools/idle/test_set_rewards.py
Add a pool for swaps and lending with [IDLE](https://idle.finance/) tokens.
=> Add IDLE pool

contracts/pools/idle/README.md, contracts/pools/idle/pooldata.json
Remove idle deployment addresses.
=> Remove deployment addresses for killed idle pool

.github/workflows/steth.yaml, contracts/pools/steth/README.md, contracts/pools/steth/StableSwapSTETH.vy, contracts/pools/steth/pooldata.json, tests/pools/common/integration/test_curve.py, tests/pools/common/unitary/test_exchange_reverts.py, tests/pools/common/unitary/test_reentrancy.py, tests/pools/common/unitary/test_remove_liquidity_one_coin.py, tests/pools/common/unitary/test_xfer_to_contract.py, tests/pools/steth/test_atoken_balances.py
Implement a pool for swaps between ETH and [stETH](0x20dC62D5904633cC6a5E34bEc87A048E80C92e97)
stETH distributes staking bonuses in the same way as Aave aTokens - the token value is always 1:1 with ETH, but the balance increases over time.  As such, this pool implementation is a mixture of logic from our [Aave](https://github.com/curvefi/curve-contract/tree/master/contracts/pools/aave) and [sETH](https://github.com/curvefi/curve-contract/tree/master/contracts/pools/seth) pools, with some additional optimizations.
Run the tests.
=> stETH pool

contracts/pools/yv2/README.md, contracts/pools/yv2/StableSwapYv2.vy, contracts/pools/yv2/pooldata.json, tests/pools/common/integration/test_virtual_price_increases.py, tests/pools/common/unitary/test_exchange_underlying.py
Signed-off-by: Andre Cronje <andre.cronje@yearn.finance>
Related issue: #
=> Added yv2 pool for compound, cream, iron bank, and more

contracts/pools/ib/README.md, contracts/pools/ib/StableSwapIB.vy, contracts/pools/ib/pooldata.json, tests/pools/common/integration/test_virtual_price_increases.py, tests/pools/common/unitary/test_exchange_underlying.py
Modified for assert == False on transfer & transferFrom
Added oracle
Signed-off-by: Andre Cronje <andre.cronje@yearn.finance>
Updated all transfer & transferFrom with assert == False
previous_balances & block_timestamp_last for oracle lookups
=> Iron Bank pool

.github/workflows/link.yaml, contracts/pools/link/README.md, contracts/pools/link/StableSwapLINK.vy, contracts/pools/link/pooldata.json, tests/fixtures/coins.py
Signed-off-by: Andre Cronje <andre.cronje@yearn.finance>
Created a native pool for LINK/sLINK
Used EURS as a template, added _update()
=> Pool for LINK/sLINK to allow for LINK cross-asset swaps

.github/workflows/usdp.yaml, contracts/pools/usdp/DepositUSDP.vy, contracts/pools/usdp/README.md, contracts/pools/usdp/StableSwapUSDP.vy, contracts/pools/usdp/pooldata.json
Support for USDP <> 3p
Added _previous_balances
Added _twap
Refactored to remove RATES and PRECISION_MUL
USDP pool based on pool-templates/meta
=> USDP pool based on pool-templates/meta

contracts/pools/usdp/README.md, contracts/pools/usdp/StableSwapUSDP.vy, contracts/pools/usdp/pooldata.json
Updates to USDP pool using `pool-templates/meta`
=> fix: redo usdp from template

contracts/pools/3pool/pooldata.json, contracts/pools/aave/pooldata.json, contracts/pools/aeth/pooldata.json, contracts/pools/busd/pooldata.json, contracts/pools/compound/pooldata.json, contracts/pools/hbtc/pooldata.json, contracts/pools/ib/pooldata.json, contracts/pools/pax/pooldata.json, contracts/pools/ren/pooldata.json, contracts/pools/saave/pooldata.json, contracts/pools/sbtc/pooldata.json, contracts/pools/susd/pooldata.json, contracts/pools/usdt/pooldata.json, contracts/pools/y/pooldata.json
Added missing data of some pools.  
Fixed some names of coins.  
Added `underlying_name` for underlying coin(need in curve-mocks).
Copied from deployments.
Changed data does not affect anything.
=> chore: Add missing pool data
